### PR TITLE
add more TensorRT support

### PR DESCRIPTION
**Pull request by bobo0810**

### CODE REVIEW

**Comment by HUI11126** [comment]
请问，你是在pytorch虚拟环境中安装的tensorrt吗？我在pytorch虚拟环境外面安装了tensorrt，但是运行/torch2tensorrt/main.py时报错了

> import tensorrt as trt
ModuleNotFoundError: No module named 'tensorrt'

**Comment by bobo0810** [comment]
> 请问，你是在pytorch虚拟环境中安装的tensorrt吗？我在pytorch虚拟环境外面安装了tensorrt，但是运行/torch2tensorrt/main.py时报错了

1.我使用的是云平台（自带环境）
2.本机也装过，请注意TensorRT版本与CUDA版本严格对应。
网上安装教程很多，可参考
 [TensorRT安装](http://zengzeyu.com/2020/07/09/tensorrt_01_installation/)
[TensorRT安装](https://blog.csdn.net/QFJIZHI/article/details/107335865)

**Comment by HUI11126** [comment]
> > 请问，你是在pytorch虚拟环境中安装的tensorrt吗？我在pytorch虚拟环境外面安装了tensorrt，但是运行/torch2tensorrt/main.py时报错了
> 
> 1.我使用的是云平台（自带环境）
> 2.本机也装过，请注意TensorRT版本与CUDA版本严格对应。
> 网上安装教程很多，可参考
> [TensorRT安装](http://zengzeyu.com/2020/07/09/tensorrt_01_installation/)
> [TensorRT安装](https://blog.csdn.net/QFJIZHI/article/details/107335865)

你好，我从nvidia官网上下载了Tensorrt的安装包，用pip安装tensorrt之后，解决了import tensorrt as trt报错的问题，但是运行/torch2tensorrt/main.py 时，报错了。我的cuda是用deb格式安装的，pytorch虚拟环境里面是用tar解压之后pip安装whl。请问，你当时是怎么安装的cuda？
loading onnx file from path ../weights/last.onnx ...
Begining onnx file parsing
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:222: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:222: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:222: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:222: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:222: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:222: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:222: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:222: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] ERROR: Network must have at least one output
[TensorRT] ERROR: Network validation failed.
Traceback (most recent call last):
  File "/home/yinshaohui/Dongguan_Project/yolov5-car-plate/torch2tensorrt/main.py", line 90, in <module>
    yolo_trt_model=YoloTrtModel(device,onnx_model_path,fp16_mode)
  File "/home/yinshaohui/Dongguan_Project/yolov5-car-plate/torch2tensorrt/yolo_trt_model.py", line 29, in __init__
    ONNX_to_TensorRT(fp16_mode=fp16_mode,onnx_model_path=onnx_model_path,trt_engine_path=trt_engine_path)
  File "/home/yinshaohui/Dongguan_Project/yolov5-car-plate/torch2tensorrt/tensorrt_com.py", line 183, in ONNX_to_TensorRT
    f.write(engine.serialize())  # 序列化
AttributeError: 'NoneType' object has no attribute 'serialize'
Completed parsing of onnx file
Building an engine from file../weights/last.onnx' this may take a while...
Completed creating Engine

Process finished with exit code 1

**Comment by HUI11126** [comment]
在/TensorRT-7.0.0.11/samples/sampleMNIST目录下编译，没有报错

(pytorch-yolov5) yinshaohui@sysadmin-System-Product-Name:~/TensorRT-7.0.0.11/samples/sampleMNIST$ make -j8
if [ ! -d ../../bin/chobj/../common ]; then mkdir -p ../../bin/dchobj/../common; fi; :
if [ ! -d ../../bin/chobj/../common ]; then mkdir -p ../../bin/dchobj/../common; fi; :
if [ ! -d ../../bin/chobj/../common ]; then mkdir -p ../../bin/dchobj/../common; fi; :
if [ ! -d ../../bin/chobj/../common ]; then mkdir -p ../../bin/dchobj/../common; fi; :
if [ ! -d ../../bin/chobj/../common ]; then mkdir -p ../../bin/dchobj/../common; fi; :
if [ ! -d ../../bin/chobj/../common ]; then mkdir -p ../../bin/dchobj/../common; fi; :
if [ ! -d ../../bin/chobj/../common ]; then mkdir -p ../../bin/dchobj/../common; fi; :
if [ ! -d ../../bin/chobj/../common ]; then mkdir -p ../../bin/chobj/../common; fi; :
Compiling: ../common/logger.cpp
Compiling: ../common/sampleOptions.cpp
Compiling: ../common/getOptions.cpp
Compiling: ../common/sampleReporting.cpp
Compiling: ../common/sampleInference.cpp
Compiling: sampleMNIST.cpp
Compiling: sampleMNIST.cpp
Compiling: ../common/sampleEngines.cpp
if [ ! -d ../../bin/chobj/../common ]; then mkdir -p ../../bin/chobj/../common; fi; :
Compiling: ../common/sampleInference.cpp
Linking: ../../bin/sample_mnist
Linking: ../../bin/sample_mnist_debug
# Copy every EXTRA_FILE of this sample to bin dir

但是没有生成编译文件 sample_mnist
(pytorch-yolov5) yinshaohui@sysadmin-System-Product-Name:~/TensorRT-7.0.0.11/samples/sampleMNIST$ ls
Makefile  README.md  sampleMNIST.cpp

**Comment by HUI11126** [comment]
楼主，你的pytorch版本是多少？

**Comment by bobo0810** [comment]
@HUI11126 目前代码仅支持TensorRT固定尺度推理，尺度由Pytorch转ONNX时确的定。

若想改变尺度，（1）Pytorch转ONNX时指定形状  （2）main.py中图像预处理部分。

**Comment by HUI11126** [comment]
楼主你好。我运行export.py生成onnx之后，转trt报了
pycuda._driver.LogicError: cuMemcpyHtoDAsync failed: invalid argument
的错误，有人说需要把输入图片做一下转换

> 在ONNX中的输入是不支持float64为,只支持单精度的数据格式, 而我自己在tensorRT里的输入没有这么转, 输入了float64的图片,所以报错, 把它改成float32 就稳了
[https://blog.csdn.net/GungnirsPledge/article/details/108428651](url)

请问，在export.py哪里做转换呢？

/home/yinshaohui/anaconda3/envs/pytorch-yolov5/bin/python /home/yinshaohui/Dongguan_Project/yolov5-car-plate/torch2tensorrt/main.py
img type:  <class 'torch.Tensor'>
img shape: torch.Size([1, 3, 1920, 1920])
orgimg shape: (1920, 1920, 3)
loading onnx file from path /home/yinshaohui/Dongguan_Project/yolov5-car-plate/weights/last.onnx ...
Begining onnx file parsing
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:222: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:222: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:222: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:222: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:222: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:222: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:222: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:222: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: Half2 support requested on hardware without native FP16 support, performance will be negatively affected.
Completed parsing of onnx file
Building an engine from file/home/yinshaohui/Dongguan_Project/yolov5-car-plate/weights/last.onnx' this may take a while...
Completed creating Engine
TensorRT file in /home/yinshaohui/Dongguan_Project/yolov5-car-plate/weights/last.trt
============ONNX->TensorRT SUCCESS============
Reading engine from file: /home/yinshaohui/Dongguan_Project/yolov5-car-plate/weights/last.trt
[TensorRT] WARNING: Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
Traceback (most recent call last):
  File "/home/yinshaohui/Dongguan_Project/yolov5-car-plate/torch2tensorrt/main.py", line 96, in <module>
    pred=yolo_trt_model(img.cpu().numpy()) #tensorrt推理
  File "/home/yinshaohui/Dongguan_Project/yolov5-car-plate/torch2tensorrt/yolo_trt_model.py", line 55, in __call__
    trt_outputs = Do_Inference(context, bindings=bindings, inputs=inputs, outputs=outputs, stream=stream)  # numpy data
  File "/home/yinshaohui/Dongguan_Project/yolov5-car-plate/torch2tensorrt/tensorrt_com.py", line 85, in Do_Inference
    [cuda.memcpy_htod_async(inp.device, inp.host, stream) for inp in inputs]
  File "/home/yinshaohui/Dongguan_Project/yolov5-car-plate/torch2tensorrt/tensorrt_com.py", line 85, in <listcomp>
    [cuda.memcpy_htod_async(inp.device, inp.host, stream) for inp in inputs]
pycuda._driver.LogicError: cuMemcpyHtoDAsync failed: invalid argument

Process finished with exit code 1

**Comment by HUI11126** [comment]
export.py文件里面，我只改了图片大小
`    parser.add_argument('--img-size', nargs='+', type=int, default=[1088, 1920], help='image size')  # height, width`

**Comment by bobo0810** [comment]
> export.py文件里面，我只改了图片大小 ` parser.add_argument('--img-size', nargs='+', type=int, default=[1088, 1920], help='image size') # height, width`

警告 没关系，结果正确就行。

**Comment by HUI11126** [comment]
> > export.py文件里面，我只改了图片大小 ` parser.add_argument('--img-size', nargs='+', type=int, default=[1088, 1920], help='image size') # height, width`
> 
> INT64 to INT32警告无影响，可不用理会。如果修改了输入尺寸，也相应修改[输出特征图的大小](https://github.com/deepcam-cn/yolov5-face/blob/56ce2426647fe3e5c656cf72a1b93f6c0d5a82e0/torch2tensorrt/yolo_trt_model.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L34)。
> 
> 举例：输入为640x640，降8、16、32倍，特征图输出为80x80、40x40、20x20.

我把输入图片改成640*640，但是还是报了shape不匹配
img shape: torch.Size([1, 3, 640, 640])
orgimg shape: (640, 640, 3)
Traceback (most recent call last):
  File "/home/yinshaohui/Dongguan_Project/yolov5-car-plate/torch2tensorrt/main.py", line 97, in <module>
    pred=yolo_trt_model(img.cpu().numpy()) #tensorrt推理
  File "/home/yinshaohui/Dongguan_Project/yolov5-car-plate/torch2tensorrt/yolo_trt_model.py", line 58, in __call__
    stride_8 = trt_outputs[0].reshape(*self.stride8_shape) # 输出形状由一维转为指定形状
ValueError: cannot reshape array of size 102400 into shape (1,3,80,80,16)

yolo_trt_model.py里面的特征图大小是：
        # 输出特征
        self.stride8_shape=(1,3,80,80,16)
        self.stride16_shape=(1,3,40,40,16)
        self.stride32_shape=(1,3,20,20,16)

**Comment by bobo0810** [comment]
@HUI11126 102400=1*1*80*80*16 ，代码里改网络输出了吗？第2维（即特征通道）为1？

**Comment by HUI11126** [comment]
> @HUI11126 102400=1_1_80_80_16 ，代码里改网络输出了吗？第2维（即特征通道）为1？

我是跑的别人的模型[https://github.com/xialuxi/yolov5-car-plate](url)

我对比了train.py和yolov5s.yaml文件，没发现是否改了网络输出，应该去哪里找作者是否改了网络输出呢？


另，如果我把self.stride8_shape=(1,3,80,80,16) 改成 self.stride8_shape=(1,1,80,80,16)，会报list index out of range

**Comment by bobo0810** [comment]
> 我是跑的别人的模型[https://github.com/xialuxi/yolov5-car-plate](url)


1. yolov5-face 输出16=4（box坐标）+1（置信度）+10（5个人脸关键点）+1（类别）。yolov5-car-plate的输出可能不适用。
WechatIMG1164
2. YOLOv5官方库在不断更新，当前已V6版本。从不同时间段分支出来的仓库不一定兼容。

**Comment by HUI11126** [comment]
> https://github.com/xialuxi/yolov5-car-plate

yolov5-car-plate的作者是参考yolov5-face改的，只是把人脸的角点换成了车牌的角点，关键点由5个变成了4个

**Comment by HUI11126** [comment]
我用netron查看了一下我的onnx模型，输出是对的
format
ONNX v6
producer
pytorch 1.8
imports
ai.onnx v12
data
name: data
type: float32[1,3,640,640]
stride_8
name: stride_8
type: float32[1,3,80,80,14]
stride_16
name: stride_16
type: float32[1,3,40,40,14]
stride_32
name: stride_32
type: float32[1,3,20,20,14]

**Comment by cvanilla** [comment]
> > > export.py文件里面，我只改了图片大小 ` parser.add_argument('--img-size', nargs='+', type=int, default=[1088, 1920], help='image size') # height, width`
> > 
> > 
> > INT64 to INT32警告无影响，可不用理会。如果修改了输入尺寸，也相应修改[输出特征图的大小](https://github.com/deepcam-cn/yolov5-face/blob/56ce2426647fe3e5c656cf72a1b93f6c0d5a82e0/torch2tensorrt/yolo_trt_model.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L34)。
> > 举例：输入为640x640，降8、16、32倍，特征图输出为80x80、40x40、20x20.
> 
> 我把输入图片改成640*640，但是还是报了shape不匹配 img shape: torch.Size([1, 3, 640, 640]) orgimg shape: (640, 640, 3) Traceback (most recent call last): File "/home/yinshaohui/Dongguan_Project/yolov5-car-plate/torch2tensorrt/main.py", line 97, in pred=yolo_trt_model(img.cpu().numpy()) #tensorrt推理 File "/home/yinshaohui/Dongguan_Project/yolov5-car-plate/torch2tensorrt/yolo_trt_model.py", line 58, in **call** stride_8 = trt_outputs[0].reshape(*self.stride8_shape) # 输出形状由一维转为指定形状 ValueError: cannot reshape array of size 102400 into shape (1,3,80,80,16)
> 
> yolo_trt_model.py里面的特征图大小是： # 输出特征 self.stride8_shape=(1,3,80,80,16) self.stride16_shape=(1,3,40,40,16) self.stride32_shape=(1,3,20,20,16)

请问这个问题解决了吗？我在转换的过程中也遇到了这个问题，看起来转换得到的output不符合预期

**Pull request merged**
