### PR TITLE
support export onnx/pb with output concat

### PR DESCRIPTION
**Pull request by changhy666**
verified ok! giving a value to slince variable is not support in exporting onnx or pb, such as op like '...' or ':'. if want get the output concat, please edit models/export.py like this: model.model[-1].export = False  # set Detect() layer export=True
model.model[-1].export_cat = True

### CODE REVIEW

**Comment by bobo0810** [comment]
> verified ok! giving a value to slince variable is not support in exporting onnx or pb, such as op like '...' or ':'. if want get the output concat, please edit models/export.py like this: model.model[-1].export = False # set Detect() layer export=True model.model[-1].export_cat = True


There are problems with the ONNX model，because there was an error when I used onnx-simplifier
`onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Node (Mul_782) Op (Mul) [ShapeInferenceError] Incompatible dimensions`


I changed two places:

1.https://github.com/deepcam-cn/yolov5-face/blob/0f695a0fad36a2d2299aa3afa4f05eceb344228b/models/export.py#L63

```
model.model[-1].export = False  # set Detect() layer export=True
model.model[-1].export_cat = True
```

2.https://github.com/deepcam-cn/yolov5-face/blob/0f695a0fad36a2d2299aa3afa4f05eceb344228b/models/export.py#L71

```
output_names=['output']
```

**Comment by bobo0810** [comment]
The same error occurs when trying to predict using onnx
```
[ONNXRuntimeError] : 1 : FAIL : Load model from yolov5n-0.5.onnx failed:Node (Mul_782) Op (Mul) [ShapeInferenceError] Incompatible dimensions
```

The prediction code is as follows
```
import onnxruntime
providers = ['CUDAExecutionProvider', 'CPUExecutionProvider'] if torch.cuda.is_available() else ['CPUExecutionProvider']
session = onnxruntime.InferenceSession(onnx_weights, providers=providers)
```

**Comment by luisfmnunes** [comment]
I also tried to inference from the model generated from this change and got a runtime error. I named the outputs as outputs_32 just to store the max stride info in the output, the following result was obtained using onnxruntime:

```
[ INFO ] Creating ONNX session from model /home/luisnunes/Documents/yolov5m-face.onnx
[ INFO ] Model Inputs:
        [0] - data
[ INFO ] Model Outputs:
        [0] - outputs_32
[ INFO ] Maximum Stride = 32
2021-12-15 10:56:40.492745410 [E:onnxruntime:, sequential_executor.cc:346 Execute] Non-zero status code returned while running Mul node. Name:'Mul_619' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/math/element_wise_ops.h:505 void onnxruntime::BroadcastIterator::Append(ptrdiff_t, ptrdiff_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 3 by 21

Traceback (most recent call last):
  File "onnx_det.py", line 104, in <module>
    main(parseArguments(sys.argv[1:]))
  File "onnx_det.py", line 79, in main
    pred = model.run(onames, {input_name: img})
  File "/home/luisnunes/openvino/penv/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 188, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Mul node. Name:'Mul_619' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/math/element_wise_ops.h:505 void onnxruntime::BroadcastIterator::Append(ptrdiff_t, ptrdiff_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 3 by 21
```

**Comment by bobo0810** [comment]
The bug has been fixed, please refer to https://github.com/deepcam-cn/yolov5-face/pull/108

**Pull request merged**
